name: Doxygen

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install base dependencies
      run: |
        sudo apt update;
        sudo apt -y install doxygen graphviz
    - name: doxygen Doxyfile
      run: doxygen Doxyfile
